removed car_demo as a submodule and commented out missing header file Control.h to avoid this error
In file included from
/home/febbo/Documents/workspace/Autoware/ros/src/system/gazebo/car_demo/car_demo/plugins/PriusHybridPlugin.cc:27:0:
/home/febbo/Documents/workspace/Autoware/ros/src/system/gazebo/car_demo/car_demo/plugins/PriusHybridPlugin.hh:29:32:
fatal error: prius_msgs/Control.h: No such file or directory